name: csso_transformer
version: 0.1.0
author: Boris Kaul <localvoid@gmail.com>
description: Transfomer that minifies css files with csso tool.
homepage: https://github.com/localvoid/csso_transformer
environment:
  sdk: '>=1.6.0-dev.9.3'
dependencies:
  barback: '>=0.15.0 <0.16.0'
  path: '>=1.3.0 <2.0.0'
